name: Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "lib/commonmarker/version.rb"

jobs:
  build:
    uses: yettoapp/actions/.github/workflows/ruby_rust_test_build.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      include_musl: false
